# Generated by Django 3.1.4 on 2020-12-27 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(db_index=True, upload_to='not_used')),
            ],
        ),
        migrations.CreateModel(
            name='Schemas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('column_separators', models.CharField(choices=[(',', 'Comma "," '), (';', 'Semicolon ";"'), ('/', 'Slush "/"'), ('"', 'Double quotes """'), ('|', 'Pipe "|"')], default=',', max_length=1)),
                ('string_chapter', models.CharField(choices=[(',', 'Comma "," '), (';', 'Semicolon ";"'), ('/', 'Slush "/"'), ('"', 'Double quotes """'), ('|', 'Pipe "|"')], default='"', max_length=1)),
                ('data', models.DateField(auto_now_add=True)),
                ('rows', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('Full Name', 'Full Name'), ('Integer', 'Integer'), ('Email', 'Email'), ('Job', 'Job'), ('Phone', 'Phone')], max_length=254)),
                ('schemas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.schemas')),
            ],
        ),
    ]
